version: '3.8'

services:
  service_a:
    build:
      context: .
      dockerfile: ./service_a/Dockerfile
    ports:
      - "8080:8080"

  service_b:
    build:
      context: .
      dockerfile: ./service_b/Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - service_b/.env

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"